// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Omini.Opme.Infrastructure.Contexts;

#nullable disable

namespace Omini.Opme.Infrastructure.Migrations
{
    [DbContext(typeof(OpmeContext))]
    [Migration("20240606001734_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("hospitalcode_sequence");

            modelBuilder.HasSequence("insurancecompanycode_sequence");

            modelBuilder.HasSequence("internalspecialistcode_sequence");

            modelBuilder.HasSequence("itemcode_sequence");

            modelBuilder.HasSequence("patientcode_sequence");

            modelBuilder.HasSequence("physiciancode_sequence");

            modelBuilder.Entity("Omini.Opme.Domain.Admin.InternalSpecialist", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('internalspecialistcode_sequence')");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("InternalSpecialists", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "1",
                            CreatedBy = new Guid("93191413-db51-4cc8-bc58-cc80e180a551"),
                            CreatedOn = new DateTime(2024, 6, 6, 0, 17, 34, 177, DateTimeKind.Utc).AddTicks(5950),
                            Email = "comercial@fratermedical.com.br",
                            Telefone = "(11) 3829-9400"
                        });
                });

            modelBuilder.Entity("Omini.Opme.Domain.Admin.OpmeUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OpmeUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6211f68-cfcd-40e9-a31a-bd0dcf4b4052"),
                            CreatedBy = new Guid("93191413-db51-4cc8-bc58-cc80e180a551"),
                            CreatedOn = new DateTime(2024, 6, 6, 0, 17, 34, 177, DateTimeKind.Utc).AddTicks(6100),
                            Email = "dacceto@gmail.com",
                            IsDeleted = false,
                            UpdatedBy = new Guid("93191413-db51-4cc8-bc58-cc80e180a551"),
                            UpdatedOn = new DateTime(2024, 6, 6, 0, 17, 34, 177, DateTimeKind.Utc).AddTicks(6110)
                        },
                        new
                        {
                            Id = new Guid("77e48701-6371-4e3e-8d92-9db4a2bc1e5f"),
                            CreatedBy = new Guid("93191413-db51-4cc8-bc58-cc80e180a551"),
                            CreatedOn = new DateTime(2024, 6, 6, 0, 17, 34, 177, DateTimeKind.Utc).AddTicks(6110),
                            Email = "guilherme_or@outlook.com",
                            IsDeleted = false,
                            UpdatedBy = new Guid("93191413-db51-4cc8-bc58-cc80e180a551"),
                            UpdatedOn = new DateTime(2024, 6, 6, 0, 17, 34, 177, DateTimeKind.Utc).AddTicks(6110)
                        });
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Hospital", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('hospitalcode_sequence')");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("Hospitals", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.InsuranceCompany", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('insurancecompanycode_sequence')");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("InsuranceCompanies", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Patient", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('patientcode_sequence')");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Physician", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('physiciancode_sequence')");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Crm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Cro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("Physicians", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.Sales.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HospitalCode")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InsuranceCompanyCode")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InsuranceCompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InternalSpecialistCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Number"));

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayingSourceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayingSourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayingSourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhysicianCode")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhysicianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HospitalCode");

                    b.HasIndex("InsuranceCompanyCode");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PhysicianCode");

                    b.ToTable("Quotations", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.Sales.QuotationItem", b =>
                {
                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineId")
                        .HasColumnType("integer");

                    b.Property<string>("AnvisaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AnvisaDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("LineOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("QuotationId", "LineId");

                    b.HasIndex("ItemCode");

                    b.ToTable("QuotationItems", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.Warehouse.Item", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("nextval ('itemcode_sequence')");

                    b.Property<string>("AnvisaCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("AnvisaDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cst")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NcmCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SalesName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SusCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Uom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Code");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("Omini.Opme.Domain.Admin.InternalSpecialist", b =>
                {
                    b.OwnsOne("Omini.Opme.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<string>("InternalSpecialistCode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("InternalSpecialistCode");

                            b1.ToTable("InternalSpecialists");

                            b1.WithOwner()
                                .HasForeignKey("InternalSpecialistCode");

                            b1.HasData(
                                new
                                {
                                    InternalSpecialistCode = "1",
                                    FirstName = "Nathália",
                                    LastName = "Camelo"
                                });
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Hospital", b =>
                {
                    b.OwnsOne("Omini.Opme.Domain.ValueObjects.CompanyName", "Name", b1 =>
                        {
                            b1.Property<string>("HospitalCode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LegalName");

                            b1.Property<string>("TradeName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TradeName");

                            b1.HasKey("HospitalCode");

                            b1.ToTable("Hospitals");

                            b1.WithOwner()
                                .HasForeignKey("HospitalCode");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.InsuranceCompany", b =>
                {
                    b.OwnsOne("Omini.Opme.Domain.ValueObjects.CompanyName", "Name", b1 =>
                        {
                            b1.Property<string>("InsuranceCompanyCode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("LegalName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LegalName");

                            b1.Property<string>("TradeName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TradeName");

                            b1.HasKey("InsuranceCompanyCode");

                            b1.ToTable("InsuranceCompanies");

                            b1.WithOwner()
                                .HasForeignKey("InsuranceCompanyCode");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Patient", b =>
                {
                    b.OwnsOne("Omini.Opme.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<string>("PatientCode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("PatientCode");

                            b1.ToTable("Patients");

                            b1.WithOwner()
                                .HasForeignKey("PatientCode");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.BusinessPartners.Physician", b =>
                {
                    b.OwnsOne("Omini.Opme.Domain.ValueObjects.PersonName", "Name", b1 =>
                        {
                            b1.Property<string>("PhysicianCode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("LastName");

                            b1.Property<string>("MiddleName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("MiddleName");

                            b1.HasKey("PhysicianCode");

                            b1.ToTable("Physicians");

                            b1.WithOwner()
                                .HasForeignKey("PhysicianCode");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.Sales.Quotation", b =>
                {
                    b.HasOne("Omini.Opme.Domain.BusinessPartners.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omini.Opme.Domain.BusinessPartners.InsuranceCompany", "InsuranceCompany")
                        .WithMany()
                        .HasForeignKey("InsuranceCompanyCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omini.Opme.Domain.BusinessPartners.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omini.Opme.Domain.BusinessPartners.Physician", "Physician")
                        .WithMany()
                        .HasForeignKey("PhysicianCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("InsuranceCompany");

                    b.Navigation("Patient");

                    b.Navigation("Physician");
                });

            modelBuilder.Entity("Omini.Opme.Domain.Sales.QuotationItem", b =>
                {
                    b.HasOne("Omini.Opme.Domain.Warehouse.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Omini.Opme.Domain.Sales.Quotation", null)
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Omini.Opme.Domain.Sales.Quotation", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
