version: '3'

services:
    opme:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - DOTNET_ENVIRONMENT=Development
            - DOTNET_NUGET_SIGNATURE_VERIFICATION=false
            - USER_SECRETS_ID=94bfec52-89be-4316-a97d-8dfb1d797edd
        volumes:
            - ~/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
