name: 'Terraform setup and plan'
description: 'Setup Terraform and creates plan'
inputs:
  azure_client_id:
    description: 'Azure client id'
    required: true
  azure_tenant_id:
    description: 'Azure tenant id'
    required: true
  azure_subscription_id:
    description: 'Azure subscription id'
    required: true
  new_relic_license_key:
    description: 'New relice license key'
    required: true
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
    default: 1.8.4

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}
        terraform_wrapper: false

    - id: 'auth'
      name: 'Authenticate to Azure'
      uses: 'azure/login@v2'
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ inputs.azure_client_id }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
        ARM_USE_OIDC: true
      run: |
        terraform init

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      env:
        ARM_CLIENT_ID: ${{ inputs.azure_client_id }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
        ARM_USE_OIDC: true
        new_relic_license_key: ${{ inputs.new_relic_license_key }}
      shell: bash
      run: |
        terraform plan -no-color -out=tfplan

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v4
      with:
        # name: ${{ inputs.pr_id }}-tf-plan
        name: tfplan
        path: ${{ inputs.terraform_directory }}/tfplan

    # - name: Comment Plan
    #   id: comment-plan
    #   uses: peter-evans/create-or-update-comment@v2
    #   with:
    #     token: ${{ inputs.github_token }}
    #     issue-number: ${{ inputs.pr_id }}
    #     body: |
    #       Terraform Plan:

    #       ```
    #       ${{ steps.plan.outputs.plan }}
    #       ```

    #       Plan saved to GH artifacts.