CREATE TABLE items (
	"ID" UUID NOT NULL,
	"Code" VARCHAR(50) NOT NULL,
	"Name" VARCHAR(400) NOT NULL,
	"SalesName" VARCHAR(400) NOT NULL,
	"Description" VARCHAR(1000) NOT NULL,
	"Uom" VARCHAR(20) NOT NULL,
	"AnvisaCode" VARCHAR(20) NOT NULL,
	"AnvisaDueDate" TIMESTAMPTZ NOT NULL,
	"SupplierCode" VARCHAR(50) NOT NULL,
	"Cst" VARCHAR(10) NOT NULL,
	"SusCode" VARCHAR(20) NOT NULL,
	"NcmCode" VARCHAR(10) NOT NULL,
	"Createdby" UUID NOT NULL,
	"CreatedAt" TIMESTAMPTZ NOT NULL,
	"UpdatedBy" UUID NOT NULL,
	"UpdatedAt" TIMESTAMPTZ NOT NULL,
	CONSTRAINT "PK_Items" PRIMARY KEY ("ID" ASC)
);