name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  azure_client_id:
    description: 'Azure client id'
    required: true
  azure_tenant_id:
    description: 'Azure tenant id'
    required: true
  azure_subscription_id:
    description: 'Azure subscription id'
    required: true
  terraform_directory: 
    description: 'where to execute terraform'
    required: true
  terraform_version: 
    description: 'Terraform Version'
    required: true
    default: 1.8.4

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraforom_version }}
        terraform_wrapper: false

    - id: 'auth'
      name: 'Authenticate to Azure'
      uses: 'azure/login@v2'
      with:
        client-id: ${{ inputs.azure_client_id }}
        tenant-id: ${{ inputs.azure_tenant_id }}
        subscription-id: ${{ inputs.azure_subscription_id }}

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ inputs.azure_client_id }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
        ARM_USE_OIDC: true
      run: |
        terraform init

    - name: Download Plan
      id: download-plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: ${{ inputs.terraform_directory }}/tfplan

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      env:
        ARM_CLIENT_ID: ${{ inputs.azure_client_id }}
        ARM_TENANT_ID: ${{ inputs.azure_tenant_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
        ARM_USE_OIDC: true
      shell: bash
      run: |
        terraform apply tfplan/tfplan