// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/google/wire"
	"github.com/omini-services/omini-opme-be/internal/domain"
	"github.com/omini-services/omini-opme-be/internal/item/handler"
	"github.com/omini-services/omini-opme-be/internal/item/repository"
	"github.com/omini-services/omini-opme-be/internal/item/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewItemHandler(r chi.Router, db *gorm.DB) *handler.ItemHandler {
	itemRepository := repository.NewItemRepository(db)
	itemUsecase := usecase.NewItemUsecase(itemRepository)
	itemHandler := handler.NewItemHandler(r, itemUsecase)
	return itemHandler
}

// wire.go:

var (
	setItemRepositoryDependency = wire.NewSet(repository.NewItemRepository, wire.Bind(new(domain.ItemRepository), new(*repository.ItemRepository)))

	setItemUsecaseDependency = wire.NewSet(usecase.NewItemUsecase, wire.Bind(new(domain.ItemUsecase), new(*usecase.ItemUsecase)))
)
