// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/omini-services/omini-opme-be/internal/entity"
	"github.com/omini-services/omini-opme-be/internal/infra/database"
	"github.com/omini-services/omini-opme-be/internal/infra/web"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewWebItemHandler(db *gorm.DB) *web.WebItemHandler {
	itemRepository := database.NewItemRepository(db)
	webItemHandler := web.NewWebItemHandler(itemRepository)
	return webItemHandler
}

// wire.go:

var setItemRepositoryDependency = wire.NewSet(database.NewItemRepository, wire.Bind(new(entity.ItemRepositoryInterface), new(*database.ItemRepository)))
