name: Terraform Plan and Apply

on:
  push:
    branches:
      - main
    paths:
      - 'src/Terraform/**' 
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.8.4"

permissions:
  actions: write
  id-token: write
  contents: read

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    environment:
      name: 'development'
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Plan
        uses: ./.github/plan
        with:
          terraform_directory: "src/Terraform"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        #   pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
  terraform_apply:
    runs-on: ubuntu-latest
    needs: terraform_plan
    environment:
        name: 'development'
    steps:
      - uses: actions/checkout@v4

      - name: Terraform Apply
        uses: ./.github/apply
        with:
            terraform_directory: "src/Terraform"
            terraform_version: ${{ env.TERRAFORM_VERSION }}
            azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
            azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
            azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}